name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    name: deploy to aws lambda
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Zip app
        run: |
          zip -r function.zip index.js

      - name: deploy to aws lambda
        run: |
          aws lambda update-function-code --function-name RyanChristieFunction --zip-file fileb://./function.zip
